app_users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),
]

curriculum/urls.py
from django.urls import path
from . import views

app_name = 'curriculum'

urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create-lesson/', views.LessonCreateView.as_view(), name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(), name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update', views.LessonUpdateView.as_view(), name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete', views.LessonDeleteView.as_view(), name='lesson_delete'),
]

teaching_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_users.urls')),
    path('curriculum/', include('curriculum.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

curriculum/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Standard(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

class Subject(models.Model):
    subject_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, null=True)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE, related_name="subjects")
    image = models.ImageField(upload_to="Subject_Images", blank=True)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name+"-"+self.subject_id)
        super().save(*args, **kwargs)


class Lesson(models.Model):
    lesson_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=150)
    slug = models.SlugField(blank=True, null=True)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="lessons")
    position = models.PositiveIntegerField(verbose_name="Chapter number")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    videos = models.FileField(upload_to="Videos", verbose_name="Videos", blank=True)
    ppt = models.FileField(upload_to="PPT", verbose_name="presentation", blank=True)
    Notes = models.FileField(upload_to="Notes", verbose_name="Notes", blank=True)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('curriculum:lesson_list', kwargs={'standard': self.standard.slug, 'slug': self.subject.slug})
    

class Comment(models.Model):
    lesson_name = models.ForeignKey(Lesson, null=True, on_delete=models.CASCADE, related_name='comments')
    comm_name = models.CharField(max_length=100, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-" + str(self.author) + " " + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name
    
    class Meta:
        ordering = ['-date_added']

class Reply(models.Model):
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    reply_body = models.TextField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to " + str(self.comment_name.comm_name)

curriculum/forms.py
from django import forms
from .models import Lesson, Comment, Reply


class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('lesson_id', 'name', 'position', 'videos', 'ppt', 'Notes')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {'body':'Comment:', }

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter your comments here"}),
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        }
    

curriculum/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView, DetailView,
                                  FormView, CreateView, DeleteView, UpdateView)
from .models import Standard, Subject, Lesson
from .forms import LessonForm, CommentForm, ReplyForm
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
# Create your views here.

class StandardListView(ListView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'curriculum/standard_list_view.html'


class SubjectListView(DetailView):
    context_object_name = 'standard'
    model = Standard
    template_name = 'curriculum/subject_list_view.html'


class LessonListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'curriculum/lesson_list_view.html'

class LessonDetailView(DetailView, FormView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'curriculum/lesson_detail_view.html'
    form_class = CommentForm
    second_form_class = ReplyForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.form_class
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'
        
        form = self.get_form(form_class)

        if form_name == 'form' and form.is_valid():
            print('Comment Form is returned')
            return self.form_valid(form)
        elif form_name == 'form2' and form.is_valid():
            print('reply form is returned')
            return self.form2_valid(form)
    
    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_detail', kwargs={'standard': standard.slug, 'subject': subject.slug, 'slug': self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.lesson_name = self.object.comments.name
        fm.lesson_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()

        return context
# class LessonCreateView(CreateView):
#     form_class = LessonForm
#     context_object_name = 'lessons'
#     model=Lesson
#     template_name = 'curriculum/lesson_create_view.html'
    
#     def get_success_url(self):
#         self.object = self.get_object()
#         standard = self.object.standard
#         return reverse_lazy('curriculum:lesson_list', kwargs={'standard':standard.slug, 
#                                                               'slug': self.object.slug})
    
#     def form_valid(self, form, *args, **kwargs):
#         self.object = self.get_object()
#         fm = form.save(commit=False)
#         fm.created_by = self.request.user
#         fm.standard = self.object.standard
#         fm.subject = self.object
#         fm.save()
#         return HttpResponseRedirect(self.get_success_url(*args, **kwargs))
class LessonCreateView(CreateView):
    form_class = LessonForm
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'curriculum/lesson_create_view.html'
    
    def get_success_url(self):
        subject = self.object.subject
        standard = self.object.standard
        return reverse_lazy('curriculum:lesson_list', kwargs={'standard': standard.slug, 'slug': subject.slug })
    
    def form_valid(self, form, *args, **kwargs):
        subject_slug = self.kwargs.get('slug')
        subject = Subject.objects.get(slug=subject_slug)
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.standard = subject.standard
        fm.subject = subject
        fm.save()
        self.object = fm
        return HttpResponseRedirect(self.get_success_url(*args, **kwargs))

class LessonUpdateView(UpdateView):
    #fields = ('name', 'position', 'videos', 'ppt', 'Notes')
    form_class = LessonForm
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'curriculum/lesson_update_view.html'

class LessonDeleteView(DeleteView):
    #fields = ('name', 'position', 'videos', 'ppt', 'Notes')
    #form_class = LessonForm
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'curriculum/lesson_delete_view.html'
    
    def get_success_url(self):
        subject = self.object.subject
        standard = self.object.standard
        return reverse_lazy('curriculum:lesson_list', kwargs={'standard': standard.slug, 'slug': subject.slug })

curriculum/templates/curriculum/lesson_create_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Create a new lesson</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

curriculum/templates/curriculum/lesson_delete_view.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete Lesson</h1>
<p>Are you sure you want to delete ?</p>
<form method="POST">
    {% csrf_token %}
    <input class='btn btn-danger' type="submit" value="Delete">
    <a class='btn btn-warning'
        href="{% url 'curriculum:lesson_list' standard=lessons.standard.slug slug=lessons.subject.slug  %}">Cancel</a>

</form>
{% endblock %}

curriculum/templates/curriculum/lesson_detail_view.html
{% extends 'base.html' %}

{% block content %}

<p>Created on {{ lessons.created_at }} by {{ lessons.created_by }}</p>
<a class='btn btn-primary'
    href="{% url 'curriculum:lesson_update' standard=lessons.standard.slug subject=lessons.subject.slug slug=lessons.slug %}">Update</a>
<a class='btn btn-danger'
    href="{% url 'curriculum:lesson_delete' standard=lessons.standard.slug subject=lessons.subject.slug slug=lessons.slug %}">Delete</a>

<h4>Post Your comment or question below:</h4>
<form method="POST">
    <div class="form-group">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="form" value="Add Comment" class="btn btn-primary">
    </div>
</form>

{% for comment in lessons.comments.all %}
<h4>{{comment.author}}<small><i> Posted on {{ comment.date_added }}</i></small></h4>
<p>{{ comment.body }}</p>

{% for reply in comment.replies.all %}
<h5>{{ reply.author }}<small><i> Posted on {{ reply.date_added }}</i></small></h5>
<p>{{ reply.reply_body }}</p>
{% endfor %}


<!--form to post reply-->
<form method="POST">
    <div class="form-group">
        <input type="hidden" name="comment.id" value="{{comment.id}}">
        <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
        {% csrf_token %}
        {{ form2.as_p }}
        <input type="submit" name="form2" value="Add Reply" class="btn btn-warning">
    </div>
</form>
{% endfor %}
{% endblock %}

curriculum/templates/curriculum/lesson_list_view.html
{% extends 'base.html' %}
{% block content %}
{% for lesson in subjects.lessons.all %}
<a href="{% url 'curriculum:lesson_detail' slug=lesson.slug subject=subjects.slug standard=subjects.standard.slug %}"
    class="text-decoration-none">Chapter
    - {{lesson.position}} : {{ lesson.name}}</a><br>
{% endfor %}
<a href="{% url 'curriculum:lesson_create' standard=subjects.standard.slug slug=subjects.slug %}"
    class="btn btn-primary">Create
    a new Lesson</a>
{% endblock %}

curriculum/templates/curriculum/lesson_update_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Update Lesson</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update">
</form>
{% endblock %}

curriculum/templates/curriculum/standard_list_view.html
{% extends 'base.html' %}
{% block content %}
{% for standard in standards %}
<a href="{% url 'curriculum:subject_list' slug=standard.slug %}">{{standard.name}}</a><br>
{% endfor %}
{% endblock %}

curriculum/templates/curriculum/subject_list_view.html
{% extends 'base.html' %}
{% block content %}
{% for subject in standard.subjects.all %}
<a href="{% url 'curriculum:lesson_list' slug=subject.slug standard=standard.slug %}">{{ subject.name }}</a>
<p>{{ subject.description | truncatechars:75 }}</p>
{% endfor %}
{% endblock %}